name: CI

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Sync dependencies (dev)
        run: uv sync --group dev

      - name: Ruff lint
        run: uv run ruff check --output-format=github .

      - name: Ruff format check
        run: uv run ruff format --check .

      - name: Type check (mypy)
        run: uv run mypy src

      - name: Run tests with coverage
        run: |
          uv run coverage erase
          uv run coverage run -m pytest -q
          uv run coverage combine || true
          uv run coverage xml -i
          uv run coverage report

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: coverage.xml
          fail_ci_if_error: false
          verbose: true

      - name: Upload coverage XML artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-xml
          path: coverage.xml
