name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Sync dependencies (dev)
        run: uv sync --group dev

      - name: Lint (Ruff)
        run: uv run ruff check --output-format=github .

      - name: Format check (Ruff)
        run: uv run ruff format --check .

      - name: Run tests
        run: uv run pytest -q
